### PR TITLE
update

### PR DESCRIPTION
**Pull request by andreistefanciprian**

### CODE REVIEW

**Comment by andreistefanciprian** [comment]
```
Error: This repo is not allowlisted for Atlantis.
```

**Comment by andreistefanciprian** [comment]
atlantis plan

**Comment by andreistefanciprian** [comment]
```
Error: This repo is not allowlisted for Atlantis.
```

**Comment by andreistefanciprian** [comment]
atlantis plan

**Comment by andreistefanciprian** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: unmarshal errors:
  line 40: field destroy not found in type raw.Workflow
```

**Comment by andreistefanciprian** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by andreistefanciprian** [comment]
atlantis plan

**Comment by andreistefanciprian** [comment]
Ran Plan for 0 projects:

**Comment by andreistefanciprian** [comment]
atlantis plan -p dev

**Comment by andreistefanciprian** [comment]
Ran Plan for dir: `environments/dev` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 1: running "terraform init" in "/home/atlantis/.atlantis/repos/andreistefanciprian/gcp-tf-atlantis-test/2/default/environments/dev": 
[31m
[1m[31mError: [0m[0m[1mUnsupported Terraform Core version[0m

[0m  on versions.tf line 17, in terraform:
  17:   [4mrequired_version = "~> 0.13.0"[0m
[0m
This configuration does not support Terraform version 0.14.5. To proceed,
either choose another supported Terraform version or update this version
constraint. Version constraints are normally set for good reason, so updating
the constraint may lead to other errors or unexpected behavior.
[0m[0m


```
</details>

**Comment by andreistefanciprian** [comment]
Ran Plan for 2 projects:

1. project: `dev` dir: `environments/dev` workspace: `default`
1. project: `prod` dir: `environments/prod` workspace: `default`

### 1. project: `dev` dir: `environments/dev` workspace: `default`
<details><summary>Show Output</summary>

```diff

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.56.0...
- Installed hashicorp/google v3.56.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # google_compute_firewall.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_firewall" "default" {
      [32m+[0m [0m[1m[0mcreation_timestamp[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdestination_ranges[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdirection[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0menable_logging[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m               = "dev-firewall"
      [32m+[0m [0m[1m[0mnetwork[0m[0m            = "dev-network"
      [32m+[0m [0m[1m[0mpriority[0m[0m           = 1000
      [32m+[0m [0m[1m[0mproject[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0msource_ranges[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0msource_tags[0m[0m        = [
          [32m+[0m [0m"web",
        ]

      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = [
              [32m+[0m [0m"80",
              [32m+[0m [0m"8080",
              [32m+[0m [0m"1000-2000",
            ]
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "tcp"
        }
      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = []
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "icmp"
        }
    }

[1m  # google_compute_network.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_network" "default" {
      [32m+[0m [0m[1m[0mauto_create_subnetworks[0m[0m         = true
      [32m+[0m [0m[1m[0mdelete_default_routes_on_create[0m[0m = false
      [32m+[0m [0m[1m[0mgateway_ipv4[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mmtu[0m[0m                             = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                            = "dev-network"
      [32m+[0m [0m[1m[0mproject[0m[0m                         = (known after apply)
      [32m+[0m [0m[1m[0mrouting_mode[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m                       = (known after apply)
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fdev%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p dev`
</details>

---
### 2. project: `prod` dir: `environments/prod` workspace: `default`
<details><summary>Show Output</summary>

```diff

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.56.0...
- Installed hashicorp/google v3.56.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # google_compute_firewall.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_firewall" "default" {
      [32m+[0m [0m[1m[0mcreation_timestamp[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdestination_ranges[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdirection[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0menable_logging[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m               = "prod-firewall"
      [32m+[0m [0m[1m[0mnetwork[0m[0m            = "prod-network"
      [32m+[0m [0m[1m[0mpriority[0m[0m           = 1000
      [32m+[0m [0m[1m[0mproject[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0msource_ranges[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0msource_tags[0m[0m        = [
          [32m+[0m [0m"web",
        ]

      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = [
              [32m+[0m [0m"80",
              [32m+[0m [0m"8080",
              [32m+[0m [0m"1000-2000",
            ]
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "tcp"
        }
      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = []
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "icmp"
        }
    }

[1m  # google_compute_network.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_network" "default" {
      [32m+[0m [0m[1m[0mauto_create_subnetworks[0m[0m         = true
      [32m+[0m [0m[1m[0mdelete_default_routes_on_create[0m[0m = false
      [32m+[0m [0m[1m[0mgateway_ipv4[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mmtu[0m[0m                             = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                            = "prod-network"
      [32m+[0m [0m[1m[0mproject[0m[0m                         = (known after apply)
      [32m+[0m [0m[1m[0mrouting_mode[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m                       = (known after apply)
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p prod`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fprod%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p prod`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
atlantis plan -p dev

**Comment by andreistefanciprian** [comment]
Ran Plan for project: `dev` dir: `environments/dev` workspace: `default`

<details><summary>Show Output</summary>

```diff

[0m[1mInitializing the backend...[0m

[0m[1mInitializing provider plugins...[0m
- Reusing previous version of hashicorp/google from the dependency lock file
- Installing hashicorp/google v3.56.0...
- Installed hashicorp/google v3.56.0 (signed by HashiCorp)

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # google_compute_firewall.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_firewall" "default" {
      [32m+[0m [0m[1m[0mcreation_timestamp[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdestination_ranges[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdirection[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0menable_logging[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m               = "dev-firewall"
      [32m+[0m [0m[1m[0mnetwork[0m[0m            = "dev-network"
      [32m+[0m [0m[1m[0mpriority[0m[0m           = 1000
      [32m+[0m [0m[1m[0mproject[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0msource_ranges[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0msource_tags[0m[0m        = [
          [32m+[0m [0m"web",
        ]

      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = [
              [32m+[0m [0m"80",
              [32m+[0m [0m"8080",
              [32m+[0m [0m"1000-2000",
            ]
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "tcp"
        }
      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = []
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "icmp"
        }
    }

[1m  # google_compute_network.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_network" "default" {
      [32m+[0m [0m[1m[0mauto_create_subnetworks[0m[0m         = true
      [32m+[0m [0m[1m[0mdelete_default_routes_on_create[0m[0m = false
      [32m+[0m [0m[1m[0mgateway_ipv4[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mmtu[0m[0m                             = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                            = "dev-network"
      [32m+[0m [0m[1m[0mproject[0m[0m                         = (known after apply)
      [32m+[0m [0m[1m[0mrouting_mode[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m                       = (known after apply)
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fdev%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p dev`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
atlantis apply -p dev

**Comment by andreistefanciprian** [comment]
Ran Apply for project: `dev` dir: `environments/dev` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Comment by andreistefanciprian** [comment]
atlantis apply -p dev

**Comment by andreistefanciprian** [comment]
**Apply Error**
```
no working directory found–did you run plan?
```

**Comment by andreistefanciprian** [comment]
atlantis plan -p dev

**Comment by andreistefanciprian** [comment]
Ran Plan for project: `dev` dir: `environments/dev` workspace: `default`

<details><summary>Show Output</summary>

```diff

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.57.0...
- Installed hashicorp/google v3.57.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # google_compute_firewall.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_firewall" "default" {
      [32m+[0m [0m[1m[0mcreation_timestamp[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdestination_ranges[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdirection[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0menable_logging[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m               = "dev-firewall"
      [32m+[0m [0m[1m[0mnetwork[0m[0m            = "dev-network"
      [32m+[0m [0m[1m[0mpriority[0m[0m           = 1000
      [32m+[0m [0m[1m[0mproject[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0msource_ranges[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0msource_tags[0m[0m        = [
          [32m+[0m [0m"web",
        ]

      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = [
              [32m+[0m [0m"80",
              [32m+[0m [0m"8080",
              [32m+[0m [0m"1000-2000",
            ]
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "tcp"
        }
      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = []
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "icmp"
        }
    }

[1m  # google_compute_network.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_network" "default" {
      [32m+[0m [0m[1m[0mauto_create_subnetworks[0m[0m         = true
      [32m+[0m [0m[1m[0mdelete_default_routes_on_create[0m[0m = false
      [32m+[0m [0m[1m[0mgateway_ipv4[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mmtu[0m[0m                             = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                            = "dev-network"
      [32m+[0m [0m[1m[0mproject[0m[0m                         = (known after apply)
      [32m+[0m [0m[1m[0mrouting_mode[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m                       = (known after apply)
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fdev%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p dev`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
atlantis apply

**Comment by andreistefanciprian** [comment]
Ran Apply for 0 projects:

**Review by automationdevops19 — APPROVED** [review]

**Comment by automationdevops19** [comment]
atlantis apply

**Comment by andreistefanciprian** [comment]
Ran Apply for 0 projects:

**Comment by andreistefanciprian** [comment]
atlantis plan

**Comment by andreistefanciprian** [comment]
Ran Plan for 2 projects:

1. project: `dev` dir: `environments/dev` workspace: `default`
1. project: `prod` dir: `environments/prod` workspace: `default`

### 1. project: `dev` dir: `environments/dev` workspace: `default`
<details><summary>Show Output</summary>

```diff

[0m[1mInitializing the backend...[0m

[0m[1mInitializing provider plugins...[0m
- Reusing previous version of hashicorp/google from the dependency lock file
- Installing hashicorp/google v3.57.0...
- Installed hashicorp/google v3.57.0 (signed by HashiCorp)

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # google_compute_firewall.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_firewall" "default" {
      [32m+[0m [0m[1m[0mcreation_timestamp[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdestination_ranges[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdirection[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0menable_logging[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m               = "dev-firewall"
      [32m+[0m [0m[1m[0mnetwork[0m[0m            = "dev-network"
      [32m+[0m [0m[1m[0mpriority[0m[0m           = 1000
      [32m+[0m [0m[1m[0mproject[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0msource_ranges[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0msource_tags[0m[0m        = [
          [32m+[0m [0m"web",
        ]

      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = [
              [32m+[0m [0m"80",
              [32m+[0m [0m"8080",
              [32m+[0m [0m"1000-2000",
            ]
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "tcp"
        }
      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = []
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "icmp"
        }
    }

[1m  # google_compute_network.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_network" "default" {
      [32m+[0m [0m[1m[0mauto_create_subnetworks[0m[0m         = true
      [32m+[0m [0m[1m[0mdelete_default_routes_on_create[0m[0m = false
      [32m+[0m [0m[1m[0mgateway_ipv4[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mmtu[0m[0m                             = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                            = "dev-network"
      [32m+[0m [0m[1m[0mproject[0m[0m                         = (known after apply)
      [32m+[0m [0m[1m[0mrouting_mode[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m                       = (known after apply)
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fdev%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p dev`
</details>

---
### 2. project: `prod` dir: `environments/prod` workspace: `default`
<details><summary>Show Output</summary>

```diff

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.57.0...
- Installed hashicorp/google v3.57.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # google_compute_firewall.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_firewall" "default" {
      [32m+[0m [0m[1m[0mcreation_timestamp[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdestination_ranges[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdirection[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0menable_logging[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m               = "prod-firewall"
      [32m+[0m [0m[1m[0mnetwork[0m[0m            = "prod-network"
      [32m+[0m [0m[1m[0mpriority[0m[0m           = 1000
      [32m+[0m [0m[1m[0mproject[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0msource_ranges[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0msource_tags[0m[0m        = [
          [32m+[0m [0m"web",
        ]

      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = [
              [32m+[0m [0m"80",
              [32m+[0m [0m"8080",
              [32m+[0m [0m"1000-2000",
            ]
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "tcp"
        }
      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = []
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "icmp"
        }
    }

[1m  # google_compute_network.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_network" "default" {
      [32m+[0m [0m[1m[0mauto_create_subnetworks[0m[0m         = true
      [32m+[0m [0m[1m[0mdelete_default_routes_on_create[0m[0m = false
      [32m+[0m [0m[1m[0mgateway_ipv4[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mmtu[0m[0m                             = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                            = "prod-network"
      [32m+[0m [0m[1m[0mproject[0m[0m                         = (known after apply)
      [32m+[0m [0m[1m[0mrouting_mode[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m                       = (known after apply)
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p prod`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fprod%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p prod`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
atlantis apply

**Comment by andreistefanciprian** [comment]
Ran Apply for 0 projects:

**Comment by andreistefanciprian** [comment]
**Warning**: The plan for dir: `environments/dev` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by andreistefanciprian** [comment]
**Warning**: The plan for dir: `environments/prod` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Pull request merged**
