### PR TITLE
update port

### PR DESCRIPTION
**Pull request by andreistefanciprian**

### CODE REVIEW

**Comment by andreistefanciprian** [comment]
Ran Plan for project: `prod` dir: `environments/prod` workspace: `default`

<details><summary>Show Output</summary>

```diff

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.57.0...
- Installed hashicorp/google v3.57.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # google_compute_firewall.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_firewall" "default" {
      [32m+[0m [0m[1m[0mcreation_timestamp[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdestination_ranges[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdirection[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0menable_logging[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m               = "prod-firewall"
      [32m+[0m [0m[1m[0mnetwork[0m[0m            = "prod-network"
      [32m+[0m [0m[1m[0mpriority[0m[0m           = 1000
      [32m+[0m [0m[1m[0mproject[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0msource_ranges[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0msource_tags[0m[0m        = [
          [32m+[0m [0m"web",
        ]

      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = [
              [32m+[0m [0m"80",
              [32m+[0m [0m"8080",
              [32m+[0m [0m"1000-2000",
              [32m+[0m [0m"443",
            ]
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "tcp"
        }
      [32m+[0m [0mallow {
          [32m+[0m [0m[1m[0mports[0m[0m    = []
          [32m+[0m [0m[1m[0mprotocol[0m[0m = "icmp"
        }
    }

[1m  # google_compute_network.default[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "google_compute_network" "default" {
      [32m+[0m [0m[1m[0mauto_create_subnetworks[0m[0m         = true
      [32m+[0m [0m[1m[0mdelete_default_routes_on_create[0m[0m = false
      [32m+[0m [0m[1m[0mgateway_ipv4[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mmtu[0m[0m                             = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                            = "prod-network"
      [32m+[0m [0m[1m[0mproject[0m[0m                         = (known after apply)
      [32m+[0m [0m[1m[0mrouting_mode[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mself_link[0m[0m                       = (known after apply)
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p prod`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fprod%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p prod`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
atlantis apply

**Comment by andreistefanciprian** [comment]
Ran Apply for 0 projects:

**Comment by andreistefanciprian** [comment]
atlantis apply -p prod

**Comment by andreistefanciprian** [comment]
Ran Apply for project: `prod` dir: `environments/prod` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by automationdevops19 — APPROVED** [review]

**Comment by andreistefanciprian** [comment]
atlantis apply -p prod

**Comment by andreistefanciprian** [comment]
Ran Apply for project: `prod` dir: `environments/prod` workspace: `default`

```diff
[0m[1mgoogle_compute_network.default: Creating...[0m[0m
[0m[1mgoogle_compute_network.default: Still creating... [10s elapsed][0m[0m
[0m[1mgoogle_compute_network.default: Still creating... [20s elapsed][0m[0m
[0m[1mgoogle_compute_network.default: Still creating... [30s elapsed][0m[0m
[0m[1mgoogle_compute_network.default: Still creating... [40s elapsed][0m[0m
[0m[1mgoogle_compute_network.default: Creation complete after 42s [id=projects/firm-alchemy-304214/global/networks/prod-network][0m[0m
[0m[1mgoogle_compute_firewall.default: Creating...[0m[0m
[0m[1mgoogle_compute_firewall.default: Still creating... [10s elapsed][0m[0m
[0m[1mgoogle_compute_firewall.default: Creation complete after 11s [id=projects/firm-alchemy-304214/global/firewalls/prod-firewall][0m[0m
[0m[1m[32m
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.[0m

```

**Comment by andreistefanciprian** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `environments/prod` workspace: `default`

**Pull request merged**
