### PR TITLE
coment

### PR DESCRIPTION
**Pull request by andreistefanciprian**

### CODE REVIEW

**Comment by andreistefanciprian** [comment]
Ran Plan for project: `dev` dir: `environments/dev` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.57.0...
- Installed hashicorp/google v3.57.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

google_compute_network.default: Refreshing state... [id=projects/firm-alchemy-304214/global/networks/dev-network]
google_compute_firewall.default: Refreshing state... [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall]

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fdev%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p dev`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
Ran Plan for project: `dev` dir: `environments/dev` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.57.0...
- Installed hashicorp/google v3.57.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

google_compute_network.default: Refreshing state... [id=projects/firm-alchemy-304214/global/networks/dev-network]
google_compute_firewall.default: Refreshing state... [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_compute_firewall.default will be updated in-place
  ~ resource "google_compute_firewall" "default" {
        id                      = "projects/firm-alchemy-304214/global/firewalls/dev-firewall"
        name                    = "dev-firewall"
        # (13 unchanged attributes hidden)

      + allow {
          + ports    = [
              + "80",
              + "8080",
              + "1000-2000",
              + "443",
            ]
          + protocol = "tcp"
        }
      - allow {
          - ports    = [
              - "80",
              - "8080",
              - "1000-2000",
            ] -> null
          - protocol = "tcp" -> null
        }
        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/andreistefanciprian/gcp-tf-atlantis-test/6/default/environments/dev/dev-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/andreistefanciprian/gcp-tf-atlantis-test/6/default/environments/dev/dev-default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fdev%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p dev`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
atlantis apply -p dev

**Comment by andreistefanciprian** [comment]
Ran Apply for project: `dev` dir: `environments/dev` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by automationdevops19 — APPROVED** [review]

**Comment by andreistefanciprian** [comment]
atlantis apply

**Comment by andreistefanciprian** [comment]
Ran Apply for project: `dev` dir: `environments/dev` workspace: `default`

```diff
google_compute_firewall.default: Modifying... [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall]
google_compute_firewall.default: Still modifying... [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall, 10s elapsed]
google_compute_firewall.default: Modifications complete after 11s [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

**Comment by andreistefanciprian** [comment]
Ran Plan for project: `dev` dir: `environments/dev` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v3.57.0...
- Installed hashicorp/google v3.57.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

google_compute_network.default: Refreshing state... [id=projects/firm-alchemy-304214/global/networks/dev-network]
google_compute_firewall.default: Refreshing state... [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_compute_firewall.default will be updated in-place
  ~ resource "google_compute_firewall" "default" {
        id                      = "projects/firm-alchemy-304214/global/firewalls/dev-firewall"
        name                    = "dev-firewall"
        # (13 unchanged attributes hidden)

      + allow {
          + ports    = [
              + "80",
              + "8080",
              + "1000-2000",
              + "443",
              + "8090",
            ]
          + protocol = "tcp"
        }
      - allow {
          - ports    = [
              - "80",
              - "8080",
              - "1000-2000",
              - "443",
            ] -> null
          - protocol = "tcp" -> null
        }
        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/andreistefanciprian/gcp-tf-atlantis-test/6/default/environments/dev/dev-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/andreistefanciprian/gcp-tf-atlantis-test/6/default/environments/dev/dev-default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.quicksampleapp.com/lock?id=andreistefanciprian%252Fgcp-tf-atlantis-test%252Fenvironments%252Fdev%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p dev`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by andreistefanciprian** [comment]
atlantis apply

**Comment by andreistefanciprian** [comment]
Ran Apply for project: `dev` dir: `environments/dev` workspace: `default`

```diff
google_compute_firewall.default: Modifying... [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall]
google_compute_firewall.default: Still modifying... [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall, 10s elapsed]
google_compute_firewall.default: Modifications complete after 11s [id=projects/firm-alchemy-304214/global/firewalls/dev-firewall]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

**Comment by andreistefanciprian** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `environments/dev` workspace: `default`

**Pull request merged**
